_wandb:
    value:
        cli_version: 0.21.1
        e:
            cz60gdajb4du89s5j3aulugy5waymfvk:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                codePath: week7/go2_walk_pth/go2_stand (1).py
                codePathLocal: go2_stand (1).py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "201354903552"
                        used: "194406559744"
                email: starfishkid.brawlstars@gmail.com
                executable: /Users/advaitdesai/Programming/eklavya/venv/bin/python3
                git:
                    commit: 85b44502c12c177496d96e58507851525cce83c3
                    remote: git@github.com:Advait2211/quad_move_eklavya.git
                host: Advaits-M2-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.3.2-arm64-arm-64bit
                program: /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/go2_stand (1).py
                python: CPython 3.10.18
                root: /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth
                startedAt: "2025-08-19T12:02:56.735105Z"
                writerId: cz60gdajb4du89s5j3aulugy5waymfvk
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
clip_eps:
    value: 0.2
device:
    value: cpu
env_id:
    value: Ant-v5
epochs:
    value: 10
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
minibatch_size:
    value: 512
num_envs:
    value: 16
steps_per_env:
    value: 1024
