_wandb:
    value:
        cli_version: 0.21.1
        e:
            1b64l8oyn4mrqlro9dfz1qeoxx80fvka:
                email: starfishkid.brawlstars@gmail.com
                executable: /Users/advaitdesai/Programming/eklavya/venv/bin/python3
                git:
                    commit: 85b44502c12c177496d96e58507851525cce83c3
                    remote: git@github.com:Advait2211/quad_move_eklavya.git
                host: Advaits-M2-MacBook-Air.local
                os: macOS-15.3.2-arm64-arm-64bit
                program: <python with no main file>
                python: CPython 3.10.18
                root: /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth
                startedAt: "2025-08-19T12:03:06.453223Z"
                writerId: 1b64l8oyn4mrqlro9dfz1qeoxx80fvka
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
clip_eps:
    value: 0.2
device:
    value: cpu
env_id:
    value: Ant-v5
epochs:
    value: 10
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
minibatch_size:
    value: 512
num_envs:
    value: 16
steps_per_env:
    value: 1024
