_wandb:
    value:
        cli_version: 0.21.1
        e:
            lypoia6mtx6ui4etf5jew8wtqcjotys0:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "6442450944"
                codePath: arhan_execute/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "201354903552"
                        used: "188965732352"
                email: starfishkid.brawlstars@gmail.com
                executable: /Users/advaitdesai/Programming/eklavya/venv/bin/python3
                git:
                    commit: 627a4593a45a311df6c16c56e67c696a5e82bbbb
                    remote: git@github.com:Advait2211/quad_move_eklavya.git
                host: Advaits-M2-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.3.2-arm64-arm-64bit
                program: /Users/advaitdesai/Programming/eklavya/arhan_execute/main.py
                python: CPython 3.10.18
                root: /Users/advaitdesai/Programming/eklavya/arhan_execute
                startedAt: "2025-09-06T17:23:01.546558Z"
                writerId: lypoia6mtx6ui4etf5jew8wtqcjotys0
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 3
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
clip_eps:
    value: 0.2
device:
    value: cpu
env_id:
    value: Ant-v5
epochs:
    value: 5
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
num_envs:
    value: 16
num_minibatches:
    value: 32
steps_per_env:
    value: 1024
total_timesteps:
    value: 5000000
