_wandb:
    value:
        cli_version: 0.21.1
        e:
            53itgqk5ihfxcau69ay3qe13qh9pbgnw:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "7516192768"
                codePath: week7/go2_walk/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "201354903552"
                        used: "198622867456"
                email: starfishkid.brawlstars@gmail.com
                executable: /Users/advaitdesai/Programming/eklavya/venv/bin/python3
                git:
                    commit: af060125bef75d5850c68e1fb22ab92270e01077
                    remote: git@github.com:Advait2211/quad_move_eklavya.git
                host: Advaits-M2-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.3.2-arm64-arm-64bit
                program: /Users/advaitdesai/Programming/eklavya/week7/go2_walk/main.py
                python: CPython 3.10.18
                root: /Users/advaitdesai/Programming/eklavya/week7/go2_walk
                startedAt: "2025-08-15T13:58:04.285488Z"
                writerId: 53itgqk5ihfxcau69ay3qe13qh9pbgnw
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
clip_eps:
    value: 0.2
device:
    value: cpu
env_id:
    value: Ant-v5
epochs:
    value: 30
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
minibatch_size:
    value: 65536
num_envs:
    value: 128
steps_per_env:
    value: 1024
